In [44]:
import requests
import json
import gmaps
import pandas as pd

from yelpapi import get_my_key
from gkey import gkey

In [45]:
business_id = "e1zDuraqPYNqfEmgXJJAyQ"

ENDPORINT = "https://api.yelp.com/v3/businesses/search"

HEADERS = {'Authorization': 'bearer %s' % get_my_key}

In [46]:
PARAMETERS = {"term": "coffee", "limit": 50,  "radius": 10000, "location": "Chicago"} 

response = requests.get(url = ENDPORINT, params= PARAMETERS, headers=HEADERS)

business_data = response.json()

len(business_data["businesses"])

50

In [47]:
#Pick up the columns we care
good_coffee = business_data["businesses"]
good_coffee_df = pd.DataFrame(good_coffee)
good_coffee_df = good_coffee_df[["name","is_closed","categories","review_count","rating","location", "coordinates"]]
good_coffee_df.head()

,name,is_closed,categories,review_count,rating,location,coordinates
0,The Wormhole Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",1061,4.5,"{'address1': '1462 N Milwaukee Ave', 'address2...","{'latitude': 41.90828, 'longitude': -87.67471}"
1,Ipsento 606,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",215,4.5,"{'address1': '1813 N Milwaukee Ave', 'address2...","{'latitude': 41.91443, 'longitude': -87.68326}"
2,Fairgrounds Coffee and Tea,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",5,5.0,"{'address1': '1330 W Fulton Market', 'address2...","{'latitude': 41.88693, 'longitude': -87.6601}"
3,Star Lounge Coffee Bar,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",516,4.5,"{'address1': '2521 W Chicago Ave', 'address2':...","{'latitude': 41.89544, 'longitude': -87.69017}"
4,Purple Llama,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",50,4.5,"{'address1': '2140 W Division St', 'address2':...","{'latitude': 41.90338, 'longitude': -87.68131}"

In [48]:
#Give a requirement on how to define a good coffee shop
great_coffee_shop = good_coffee_df.loc[(good_coffee_df["review_count"]>50) & 
                                       ( good_coffee_df["rating"] >=4.0)]
great_coffee_shop.head()

,name,is_closed,categories,review_count,rating,location,coordinates
0,The Wormhole Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",1061,4.5,"{'address1': '1462 N Milwaukee Ave', 'address2...","{'latitude': 41.90828, 'longitude': -87.67471}"
1,Ipsento 606,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",215,4.5,"{'address1': '1813 N Milwaukee Ave', 'address2...","{'latitude': 41.91443, 'longitude': -87.68326}"
3,Star Lounge Coffee Bar,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",516,4.5,"{'address1': '2521 W Chicago Ave', 'address2':...","{'latitude': 41.89544, 'longitude': -87.69017}"
5,Sawada Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",537,4.5,"{'address1': '112 N Green St', 'address2': Non...","{'latitude': 41.8836669921875, 'longitude': -8..."
6,Spinning J,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",315,4.5,"{'address1': '1000 N California Ave', 'address...","{'latitude': 41.899391, 'longitude': -87.696991}"

In [49]:
#How many coffee shops we have
num_coffee_shop = great_coffee_shop['name'].count()
num_coffee_shop

39

In [50]:
zip_list = []
lat_list = []
lng_list = []

for i in range(0, num_coffee_shop):
    
    temp_zip = great_coffee_shop["location"].iloc[i]["zip_code"]
    zip_list.append(temp_zip)
    
    temp_lat = great_coffee_shop["coordinates"].iloc[i]["latitude"]
    lat_list.append(temp_lat)
    
    temp_lng = great_coffee_shop["coordinates"].iloc[i]["longitude"]
    lng_list.append(temp_lng)    
    
#Re-organize the dataframe
great_coffee_shop['zip_code'] = zip_list
great_coffee_shop['latitude'] = lat_list
great_coffee_shop['longitude'] = lng_list

great_coffee_shop

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Anaconda\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,name,is_closed,categories,review_count,rating,location,coordinates,zip_code,latitude,longitude
0,The Wormhole Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",1061,4.5,"{'address1': '1462 N Milwaukee Ave', 'address2...","{'latitude': 41.90828, 'longitude': -87.67471}",60622,41.908280,-87.674710
1,Ipsento 606,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",215,4.5,"{'address1': '1813 N Milwaukee Ave', 'address2...","{'latitude': 41.91443, 'longitude': -87.68326}",60647,41.914430,-87.683260
3,Star Lounge Coffee Bar,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",516,4.5,"{'address1': '2521 W Chicago Ave', 'address2':...","{'latitude': 41.89544, 'longitude': -87.69017}",60622,41.895440,-87.690170
5,Sawada Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",537,4.5,"{'address1': '112 N Green St', 'address2': Non...","{'latitude': 41.8836669921875, 'longitude': -8...",60607,41.883667,-87.648933
6,Spinning J,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",315,4.5,"{'address1': '1000 N California Ave', 'address...","{'latitude': 41.899391, 'longitude': -87.696991}",60622,41.899391,-87.696991
7,Volumes Bookcafe,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",110,4.5,"{'address1': '1474 N Milwaukee Ave', 'address2...","{'latitude': 41.9084999, 'longitude': -87.67506}",60622,41.908500,-87.675060
8,Damn Fine Coffee Bar,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",71,4.5,"{'address1': '3317 W Armitage Ave', 'address2'...","{'latitude': 41.9173326747872, 'longitude': -8...",60647,41.917333,-87.710870
9,Sip of Hope,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",64,5.0,"{'address1': '3039 W Fullerton Ave', 'address2...","{'latitude': 41.92444, 'longitude': -87.70389}",60647,41.924440,-87.703890
10,Dark Matter Coffee - The Mothership,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",197,4.5,"{'address1': '738 N Western Ave', 'address2': ...","{'latitude': 41.89508, 'longitude': -87.68723}",60612,41.895080,-87.687230
11,CC Ferns Coffee Bar & Spirits,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",132,4.5,"{'address1': '2806 W Augusta Blvd', 'address2'...","{'latitude': 41.8994049, 'longitude': -87.6970...",60622,41.899405,-87.697089
13,Ipsento,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",822,4.5,"{'address1': '2035 N Western Ave', 'address2':...","{'latitude': 41.9186515808105, 'longitude': -8...",60647,41.918652,-87.687103
15,Caffe Streets,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",324,4.0,"{'address1': '1750 W Division', 'address2': ''...","{'latitude': 41.90354, 'longitude': -87.67197}",60622,41.903540,-87.671970
16,Osmium Coffee Bar,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",239,4.5,"{'address1': '1117 W Belmont Ave', 'address2':...","{'latitude': 41.9396019, 'longitude': -87.6573...",60657,41.939602,-87.657303
17,Ritual Coffeehouse,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",94,4.5,"{'address1': '1821 W Irving Park Rd', 'address...","{'latitude': 41.9540451, 'longitude': -87.674964}",60613,41.954045,-87.674964
18,Intelligentsia Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",1150,4.0,"{'address1': '53 W Jackson Blvd', 'address2': ...","{'latitude': 41.877995, 'longitude': -87.62956...",60604,41.877995,-87.629566
19,Limitless Coffee & Tea - Fulton Market,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",93,4.0,"{'address1': '217 N Green St', 'address2': '',...","{'latitude': 41.886248, 'longitude': -87.64850...",60607,41.886248,-87.648503
20,Two Hearted Queen,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",243,5.0,"{'address1': '1201 W Roscoe St', 'address2': '...","{'latitude': 41.9433099, 'longitude': -87.65928}",60657,41.943310,-87.659280
21,Sip Coffee House & Garden,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",404,4.5,"{'address1': '1223 W Grand Ave', 'address2': '...","{'latitude': 41.8907699584961, 'longitude': -8...",60642,41.890770,-87.658325
22,Big Shoulders Coffee,False,"[{'alias': 'coffeeroasteries', 'title': 'Coffe...",260,4.5,"{'address1': '1105 W Chicago Ave', 'address2':...","{'latitude': 41.8961251, 'longitude': -87.6550...",60642,41.896125,-87.655064
24,Bang Bang Pie & Biscuits,False,"[{'alias': 'bakeries', 'title': 'Bakeries'}, {...",1050,4.5,"{'address1': '2051 N California Ave', 'address...","{'latitude': 41.91909, 'longitude': -87.696983}",60647,41.919090,-87.696983
25,Colectivo,False,"[{'alias': 'breakfast_brunch', 'title': 'Break...",203,4.0,"{'address1': '2530 N Clark St', 'address2': ''...","{'latitude': 41.9285424, 'longitude': -87.6424...",60614,41.928542,-87.642424
26,Cafe Mustache,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",245,4.0,"{'address1': '2313 N Milwaukee Ave', 'address2...","{'latitude': 41.9232653, 'longitude': -87.6976...",60647,41.923265,-87.697667
29,La Colombe Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",143,4.0,"{'address1': '1552 N Damen Ave', 'address2': '...","{'latitude': 41.9097887, 'longitude': -87.6776...",60622,41.909789,-87.677641
31,Nighthawk Chicago,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",93,4.5,"{'address1': '4744 N Kimball Ave', 'address2':...","{'latitude': 41.967905, 'longitude': -87.713583}",60625,41.967905,-87.713583
32,The Coffee Alley,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",174,4.0,"{'address1': '1152 W Taylor', 'address2': '', ...","{'latitude': 41.8694985998054, 'longitude': -8...",60607,41.869499,-87.656378
33,Six06 Cafe Bar,False,"[{'alias': 'greek', 'title': 'Greek'}, {'alias...",71,4.5,"{'address1': '1641 W Chicago Ave', 'address2':...","{'latitude': 41.89573, 'longitude': -87.66893}",60622,41.895730,-87.668930
34,Colectivo Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",69,4.5,"{'address1': '2261 N Milwaukee Ave', 'address2...","{'latitude': 41.9222326, 'longitude': -87.6960...",60647,41.922233,-87.696004
35,Standing Passengers,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",58,4.5,"{'address1': '1458 W Chicago Ave', 'address2':...","{'latitude': 41.89638, 'longitude': -87.66468}",60642,41.896380,-87.664680
36,Fairgrounds Coffee and Tea,False,"[{'alias': 'breakfast_brunch', 'title': 'Break...",214,4.5,"{'address1': '1620 N Milwaukee Ave', 'address2...","{'latitude': 41.9106987115516, 'longitude': -8...",60647,41.910699,-87.678035
37,Passion House Cafe,False,"[{'alias': 'coffeeroasteries', 'title': 'Coffe...",53,4.5,"{'address1': '2631 N Kedzie Ave', 'address2': ...","{'latitude': 41.92939, 'longitude': -87.707}",60647,41.929390,-87.707000
39,Gaslight Coffee Roasters,False,"[{'alias': 'cafes', 'title': 'Cafes'}, {'alias...",266,4.0,"{'address1': '2385 N Milwaukee Ave', 'address2...","{'latitude': 41.92458, 'longitude': -87.69972}",60647,41.924580,-87.699720
40,Goddess And The Baker,False,"[{'alias': 'cafes', 'title': 'Cafes'}, {'alias...",883,4.0,"{'address1': '33 S Wabash Ave', 'address2': ''...","{'latitude': 41.881259, 'longitude': -87.625846}",60603,41.881259,-87.625846
41,Caffe Umbria,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",158,4.5,"{'address1': '346 N Clark St', 'address2': '',...","{'latitude': 41.8887173, 'longitude': -87.6311...",60654,41.888717,-87.631108
42,Scone City,False,"[{'alias': 'bakeries', 'title': 'Bakeries'}, {...",201,4.5,"{'address1': '1632 W Division St', 'address2':...","{'latitude': 41.9034349, 'longitude': -87.66879}",60622,41.903435,-87.668790
43,HERO Coffee Bar,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",358,4.5,"{'address1': '439 S Dearborn St', 'address2': ...","{'latitude': 41.8758857, 'longitude': -87.62904}",60605,41.875886,-87.629040
44,Groundswell Coffee Roasters,False,"[{'alias': 'coffeeroasteries', 'title': 'Coffe...",65,4.5,"{'address1': '1168 W Madison St', 'address2': ...","{'latitude': 41.8817349, 'longitude': -87.6569...",60607,41.881735,-87.656930
45,Backlot Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",74,5.0,"{'address1': '3982 N Avondale Ave', 'address2'...","{'latitude': 41.9533408903263, 'longitude': -8...",60641,41.953341,-87.731934
46,La Colombe Coffee,False,"[{'alias': 'coffee', 'title': 'Coffee & Tea'}]",431,4.0,"{'address1': '955 W Randolph St', 'address2': ...","{'latitude': 41.884110942717, 'longitude': -87...",60607,41.884111,-87.651929
48,Hendrickx Belgian Bread Crafter,False,"[{'alias': 'bakeries', 'title': 'Bakeries'}, {...",486,4.5,"{'address1': '100 E Walton St', 'address2': ''...","{'latitude': 41.9002304077148, 'longitude': -8...",60611,41.900230,-87.625168

In [51]:
#Group by zip_code
great_coffee_by_zip = great_coffee_shop.groupby('zip_code')
num_coffee_by_zip = great_coffee_by_zip['name'].count()

great_coffee_by_zip_df = pd.DataFrame(num_coffee_by_zip)
great_coffee_by_zip_df = great_coffee_by_zip_df.rename(columns={"name":"Number of Coffee Shop"})
great_coffee_by_zip_df.sort_values(by = "Number of Coffee Shop",ascending=False, inplace=True)

great_coffee_by_zip_df

          Number of Coffee Shop
zip_code
60647                        10
60622                         9
60607                         5
60642                         3
60657                         2
60603                         1
60604                         1
60605                         1
60611                         1
60612                         1
60613                         1
60614                         1
60625                         1
60641                         1
60654                         1

In [52]:
# Configure the map
gmaps.configure(api_key = gkey)

locations = great_coffee_shop[["latitude", "longitude"]].astype(float)
locations.head()

    latitude  longitude
0  41.908280 -87.674710
1  41.914430 -87.683260
3  41.895440 -87.690170
5  41.883667 -87.648933
6  41.899391 -87.696991

In [53]:
coffee_shop_layer = gmaps.symbol_layer(locations, 
                                       fill_color='rgba(0, 150, 0, 0.4)',
                                       stroke_color='rgba(0, 0, 150, 0.4)', 
                                       scale=5)

fig = gmaps.figure()

fig.add_layer(coffee_shop_layer)

fig

Figure(layout=FigureLayout(height='420px'))